apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alpha-prod

bases:
  - ../../base

patchesStrategicMerge:
  - patches/replicas.yaml
  - patches/resources.yaml
  - patches/config.yaml
  - patches/ingress.yaml

resources:
  - namespace.yaml
