apiVersion: v1
kind: ConfigMap
metadata:
  name: alpha-config
data:
  redis-host: "redis"
  redis-port: "6379"
  milvus-host: "milvus"
  milvus-port: "19530"
  neo4j-uri: "bolt://neo4j:7687"
  kafka-brokers: "kafka:9092"
  mongodb-host: "mongodb"
  mongodb-port: "27017"
