apiVersion: v1
kind: Secret
metadata:
  name: agent-service-secrets
type: Opaque
stringData:
  database-url: "postgresql://postgres:postgres@postgres:5432/alpha_agent"
---
apiVersion: v1
kind: Secret
metadata:
  name: prompt-service-secrets
type: Opaque
stringData:
  database-url: "postgresql://postgres:postgres@postgres:5432/alpha_prompt"
---
apiVersion: v1
kind: Secret
metadata:
  name: memory-service-secrets
type: Opaque
stringData:
  neo4j-user: "neo4j"
  neo4j-password: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: tools-service-secrets
type: Opaque
stringData:
  mongodb-uri: "mongodb://mongodb:27017"
