apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools-service
  labels:
    app: tools-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tools-service
  template:
    metadata:
      labels:
        app: tools-service
    spec:
      containers:
      - name: tools-service
        image: alpha/tools-service:latest
        ports:
        - containerPort: 3004
        env:
        - name: DEBUG
          value: "false"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: tools-service-secrets
              key: mongodb-uri
        - name: MONGODB_DB
          value: "alpha_tools"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: alpha-config
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: alpha-config
              key: redis-port
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 60
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: tools-service
spec:
  selector:
    app: tools-service
  ports:
  - port: 80
    targetPort: 3004
  type: ClusterIP
